import { Fact, Month, Region } from '../types'

export default [
  {
    month: Month.JANUARY,
    day: 1,
    region: Region.NATIONAL,
    name: `National Blood Mary Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 1,
    region: Region.NATIONAL,
    name: `National Hangover Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 1,
    region: Region.GLOBAL,
    name: `New Year's Eve`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 1,
    region: Region.NATIONAL,
    name: `Polar Bear Plunge Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 1,
    region: Region.NATIONAL,
    name: `Solemnity of Mary`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },

  {
    month: Month.JANUARY,
    day: 2,
    region: Region.NATIONAL,
    name: `Brew Monday`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 2,
    region: Region.NATIONAL,
    name: `Happy Mew Year for Cats Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 2,
    region: Region.NATIONAL,
    name: `National Buffet Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 2,
    region: Region.NATIONAL,
    name: `National Science Fiction Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },

  {
    month: Month.JANUARY,
    day: 3,
    region: Region.NATIONAL,
    name: `Festival of Sleep Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 3,
    region: Region.NATIONAL,
    name: `International Mind-Body Wellness Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 3,
    region: Region.NATIONAL,
    name: `JRR Tolkien Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 3,
    region: Region.NATIONAL,
    name: `National Chocolate Covered Cherry Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 3,
    region: Region.NATIONAL,
    name: `National Thank God Its Monday Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },

  {
    month: Month.JANUARY,
    day: 4,
    region: Region.NATIONAL,
    name: `National Trivia Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
  {
    month: Month.JANUARY,
    day: 4,
    region: Region.NATIONAL,
    name: `National Spaghetti Day`,
    description: ``,
    origin: ``,
    uri: ``,
    active: true,
  },
] as Fact[]
